name 'housepub-win8-services'
maintainer 'Joshua Timberman'
maintainer_email 'opensource@housepub.org'
license 'apache2'
description 'Installs/Configures housepub-win8-services'
long_description 'Installs/Configures housepub-win8-services'
version '0.1.0'
